[project]
name = "lumen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docling>=2.30.0",
    "fastembed-gpu>=0.4.2",
    "qdrant-client>=1.12.1",
]
